name: Presets for input data

columns:
  - name: input-month
    description: Three-character month string
    example: 'Jan'
    required: true
    rules:
      not_empty: true
      allow_values: [ Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec ]
      length: 3
  - name: input-day
    example: '1'
    required: true
    rules:
      not_empty: true
      is_int: true
      num_min: 1
      num_max: 31
      precision: 0
  - name: input-year
    example: '2025'
    required: true
    rules:
      not_empty: true
      is_int: true
      num_min: 2009
      num_max: 2100
      precision: 0
  - name: input-price
    description: Daily price
    example: '1,000,000.01'
    required: true
    rules:
      not_empty: true
      regex: '^\d{1,3}(,?\d{3})*(\.\d{1,2})?$'
      precision_max: 2
      num_greater: 0.00
      is_trimmed: true
  - name: input-adj-close
    description: Daily adjusted close price
    example: '3.97840639'
    rules:
      not_empty: true
      regex: '^\d{1,3}(,\d{3})*(\.\d+)?$'
      is_trimmed: true
  - name: input-volume
    description: Daily volume
    example: '10,000,000'
    required: true
    rules:
      not_empty: true
      regex: '^\d{1,3}(,?\d{3})*$'
      precision: 0
      is_trimmed: true
      lenght_min: 1
