name: Presets for input data

columns:
  - name: input-month
    description: Three-character month string
    example: 'Jan'
    required: true
    rules:
      not_empty: true
      is_trimmed: true
      allow_values: [ Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec ]
  - name: input-day
    example: '1'
    required: true
    rules:
      not_empty: true
      is_trimmed: true
      is_int: true
      num_min: 1
      num_max: 31
      precision: 0
  - name: input-year
    example: '2025'
    required: true
    rules:
      not_empty: true
      is_trimmed: true
      is_int: true
      num_min: 2009
      num_max: 2100
      precision: 0
  - name: input-price
    description: Daily price
    example: '1,000,000.01'
    required: true
    rules:
      not_empty: true
      is_trimmed: true
      regex: '^\d{1,3}(,?\d{3})*(\.\d{1,2})?$'
      precision_max: 2
      num_greater: 0.00
  - name: input-adj-close
    description: Daily adjusted close price
    example: '3.97840639'
    rules:
      not_empty: true
      is_trimmed: true
      regex: '^\d{1,3}(,?\d{3})*(\.\d+)?$'
  - name: input-volume
    description: Daily volume
    example: '10,000,000'
    required: true
    rules:
      not_empty: true
      is_trimmed: true
      regex: '^\d{1,3}(,?\d{3})*$'
      precision: 0
  - name: output-date
    description: Date in YYYY-MM-DD format
    example: '2025-01-01'
    required: true
    rules:
      not_empty: true
      is_trimmed: true
      is_date: true
      date_format: Y-m-d
      date_min: 2009-01-13
  - name: output-year
    description: Year in YYYY format
    example: '2025'
    required: true
    rules:
      not_empty: true
      is_trimmed: true
      is_int: true
      num_min: 2009
  - name: output-price
    description: Daily price
    example: '1000000.01'
    required: true
    rules:
      not_empty: true
      is_trimmed: true
      is_float: true
      precision: 2
      num_greater: 0.00
  - name: output-histogram-label
    description: Bin range
    example: '5% to 10%'
    required: true
    rules:
      not_empty: true
      is_trimmed: true
      regex: '^(?:Below\s-18%|-?\d+%\sto\s-?\d+%|Above\s18%|Total\sDays)$'
  - name: output-histogram-days
    description: Count of days
    example: '123'
    required: true
    rules:
      not_empty: true
      is_trimmed: true
      is_int: true
      num_min: 0
