name: Presets for input data

columns:
  - name: output-date
    description: Date in YYYY-MM-DD format
    example: '2025-01-01'
    required: true
    rules:
      not_empty: true
      is_date: true
      date_format: Y-m-d
      date_min: 2009-01-13
  - name: output-price
    description: Daily price
    example: '1000000.01'
    required: true
    rules:
      not_empty: true
      is_trimmed: true
      is_float: true
      precision: 2
      num_greater: 0.00
