name: Historical Data Input Schema

csv:
  delimiter: '|'
  header: true

presets:
  my-preset: ./csv-preset.yaml

columns:
  - name: Month
    preset: my-preset/input-year
    example: 'Jan'
    required: true
    rules:
      not_empty: true
      allow_values: [ Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec ]
      length: 3
  - name: Day
    preset: my-preset/input-year
    example: '1'
    required: true
    rules:
      not_empty: true
      is_int: true
      num_min: 1
      num_max: 31
      precision: 0
  - name: Year
    preset: my-preset/input-year
    example: '2025'
    required: true
    rules:
      not_empty: true
      is_int: true
      num_min: 2009
      num_max: 2100
      precision: 0
  - name: Open
    preset: my-preset/input-price
  - name: High
    preset: my-preset/input-price
  - name: Low
    preset: my-preset/input-price
  - name: Close
    preset: my-preset/input-price
  - name: AdjClose
    preset: my-preset/input-price
  - name: Volume
    preset: my-preset/input-volume
