name: Presets for input data

columns:
  - name: input-price
    description: Price data
    example: '1,000,000.01'
    rules:
      not_empty: true
      regex: '^\d{1,3}(,?\d{3})*(\.\d{1,2})?$'
      precision_max: 2
      num_greater: 0.00
      is_trimmed: true
      length_min: 1
