name: Historical Data Input Schema
filename_pattern: /resources/data/historical_data.csv$/i
csv:
  delimiter: '|'
  header: true

columns:
  - name: Month
    example: 'Jan'
    required: true
    rules:
      not_empty: true
      allow_values: [ Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec ]
      length: 3
  - name: Day
    example: '1'
    required: true
    rules:
      not_empty: true
      is_int: true
      num_min: 1
      num_max: 31
      precision: 0
  - name: Year
    example: '2025'
    required: true
    rules:
      not_empty: true
      is_int: true
      num_min: 2009
      num_max: 2100
      precision: 0
  - name: open
    example: '1,000.00'
    rules:
      not_empty: true
      precision: 2
      num_greater: 0.00

  - name: high
    required: true
    rules:
      not_empty: true

  - name: low
    required: true
    rules:
      not_empty: true
  - name: close
    required: true
    rules:
      not_empty: true
  - name: adj_close
    required: true
    rules:
      not_empty: true
  - name: volume
    required: true
    rules:
      not_empty: true
