name: Output Yearly Summary Schema

csv:
  delimiter: ','
  header: true

presets:
  my-preset: ./csv-preset.yaml

columns:
  - name: Year
    preset: my-preset/output-year
  - name: Open
    preset: my-preset/output-price
  - name: High
    preset: my-preset/output-price
  - name: Low
    preset: my-preset/output-price
  - name: Close
    preset: my-preset/output-price
