ci:
  - '.github/workflows/*.yaml'
  - '.github/workflows/*.yml'
  - 'resources/config/**'
ci_update_data:
  - '.github/workflows/update_data.yaml'
ci_validation:
  - '.github/workflows/validation.yaml'
  - 'resources/config/**'
dependencies:
  - 'Cargo.toml'
  - 'Cargo.lock'
historical_data:
  - 'resources/data/historical_data.tsv'
markdown:
  - '**/*.md'
  - 'resources/data/pyspelling.wordlist.txt'
python:
  - '**/*.py'
rust:
  - 'src/*.rs'
