ci:
  - '.github/workflows/*.yaml'
  - '.github/workflows/*.yml'
  - 'resources/config/**'
dependencies:
  - 'Cargo.toml'
  - 'Cargo.lock'
historical_data:
  - 'resources/config/paths-filter.yaml'
markdown:
  - '**/*.md'
  - 'resources/data/pyspelling.wordlist.txt'
rust:
  - 'src/*.rs'
