[package]
name = "btracker"
version = "0.2.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
csv = "1.3"
plotters = "0.3"
serde = { version = "1.0", features = ["derive"] }
