name: Update Data CI

on:
  workflow_dispatch:
#  schedule:
#    - cron: "36 5 1 * *"

   env:
      INPUT_DATA_PATH: 'resources/data/historical_data.tsv'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref == 'refs/heads/master' }}

jobs:
  todo:
    name: 
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest code
        uses: actions/checkout@v4
      - name: Backup input data
        run: cp "${INPUT_DATA_PATH}" "${INPUT_DATA_PATH}_BACKUP"
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: resources/deps/pip_requirements.txt
          python-version: 3.13
      - name: Update data
        run: python src/util/update_data.py
      - name: Show changes
        run: diff "${INPUT_DATA_PATH}" "${INPUT_DATA_PATH}_BACKUP"
